console.log("hello");
console.log("hello");
try{
    console.log(a);
}catch{
    console.log("cought an error.. a is not defined");
}

console.log("hello2");
console.log("hello2");
console.log("hello2");


console.log("hello");
console.log("hello");
let a = 5;
try {
  console.log(a);
} catch(err) {
  console.log("cought an error.. a is not defined");
  console.log(err);
}

console.log("hello2");
console.log("hello2");
console.log("hello2");